# Generated by Django 4.1.3 on 2022-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('num_of_sex_partners', models.IntegerField()),
                ('first_intercourse', models.IntegerField()),
                ('num_of_pregnancies', models.IntegerField()),
                ('smokes', models.BooleanField()),
                ('smokes_years', models.IntegerField()),
                ('smokes_packs_year', models.IntegerField()),
                ('hormonal_contracpetives', models.BooleanField()),
                ('hormonal_contracpetives_years', models.IntegerField()),
                ('IUD', models.BooleanField()),
                ('IUD_years', models.IntegerField()),
                ('STDs', models.BooleanField()),
                ('STDs_number', models.IntegerField()),
                ('STD_condylomatosis', models.BooleanField()),
                ('STD_cervical_codylomatosis', models.BooleanField()),
                ('STD_vaginal_condylomatosis', models.BooleanField()),
                ('STD_vulvo_perineal_codylomatosis', models.BooleanField()),
                ('STD_syphilis', models.BooleanField()),
                ('STD_pelvic_inflammatory_disease', models.BooleanField()),
                ('STD_genital_herpes', models.BooleanField()),
                ('STD_molluscum_contagiosum', models.BooleanField()),
                ('STD_AIDS', models.BooleanField()),
                ('STD_HIV', models.BooleanField()),
                ('STD_Hepatitis_B', models.BooleanField()),
                ('STD_HPV', models.BooleanField()),
                ('STD_num_of_diagnosis', models.IntegerField()),
                ('STD_time_since_first_diagnosis', models.IntegerField()),
                ('STD_time_since_last_diagnosis', models.IntegerField()),
                ('Dx_cancer', models.BooleanField()),
                ('Dx_CIN', models.BooleanField()),
                ('Dx_HPV', models.BooleanField()),
                ('Dx', models.BooleanField()),
                ('Hinselmann', models.BooleanField(blank=True, null=True)),
                ('Schiller', models.BooleanField(blank=True, null=True)),
                ('Cytology', models.BooleanField(blank=True, null=True)),
                ('Biopsy', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
