# Generated by Django 4.1.3 on 2022-11-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancer',
            options={'verbose_name': 'Рак шейки матки', 'verbose_name_plural': 'Раковые заболевания'},
        ),
    ]
