# Generated by Django 4.1.3 on 2022-12-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer', '0002_alter_cancer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancer',
            name='STD_time_since_first_diagnosis',
        ),
        migrations.RemoveField(
            model_name='cancer',
            name='STD_time_since_last_diagnosis',
        ),
    ]
