# Generated by Django 4.1.3 on 2022-12-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('cancer', '0003_remove_cancer_std_time_since_first_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile'),
        ),
    ]
