# Generated by Django 4.1.3 on 2023-05-23 17:16

import blood_cell.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_cell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_cell',
            name='file',
            field=models.ImageField(max_length=255, null=True, upload_to=blood_cell.models.upload_to),
        ),
    ]
