# Generated by Django 4.1.3 on 2022-11-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_disease', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heart',
            options={'verbose_name': 'Заболевания сердца', 'verbose_name_plural': 'Заболевание сердца'},
        ),
    ]
