# Generated by Django 4.1.3 on 2022-11-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart_disease', '0002_alter_heart_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Heart_Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название болезни сердца')),
            ],
            options={
                'verbose_name': 'Болезнь',
                'verbose_name_plural': 'Название болезней',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='heart',
            options={'verbose_name': 'Заболевание сердца', 'verbose_name_plural': 'Заболевания сердца'},
        ),
        migrations.AddField(
            model_name='heart',
            name='disease_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='heart_disease.type_heart_disease', verbose_name='Название болезни'),
        ),
    ]
