# Generated by Django 4.1.3 on 2022-12-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_disease', '0003_type_heart_disease_alter_heart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='chol',
            field=models.IntegerField(null=True),
        ),
    ]
