# Generated by Django 4.1.3 on 2022-12-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('heart_disease', '0004_heart_chol'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile'),
        ),
    ]
